CREATE TABLE IF NOT EXISTS USERS (
    ID UUID NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS EXPENSES (
    ID  UUID NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    COST MONEY NOT NULL,
    OWNER_ID UUID NOT NULL,
    PAID BOOLEAN NOT NULL,
    PAID_AT DATE,
    CONSTRAINT FK_OWNER 
        FOREIGN KEY(OWNER_ID) 
            REFERENCES USERS(ID) 
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GAINS (
    ID UUID NOT NULL PRIMARY KEY,
    VALUE MONEY NOT NULL,
    GAINED_AT DATE DEFAULT now(),
    OWNER_ID UUID NOT NULL,
    CONSTRAINT FK_OWNER 
        FOREIGN KEY(OWNER_ID) 
            REFERENCES USERS(ID)
            ON DELETE CASCADE
);